//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acesso
    {
        public int IdAcesso { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime Dt_AcessoEntrada { get; set; }
        public Nullable<System.DateTime> Dt_AcessoSaida { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
